runtime: nodejs22

env_variables:
  #Firebase
  VITE_FIREBASE_API_KEY: "AIzaSyAIwZAfPuPobcSEvh_JF4CamSfh13aODjI"
  VITE_FIREBASE_AUTH_DOMAIN: "aigen-app.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID: "aigen-app"
  VITE_FIREBASE_STORAGE_BUCKET: "aigen-app.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID: "73681948337"
  VITE_FIREBASE_APP_ID: "1:73681948337:web:bb7729568a7ec00c501c90"
  VITE_FIREBASE_MEASUREMENT_ID: "G-9PG3WXBSKF"
  #OpenAI
  VITE_OPENAI_API_KEY: "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"
  #PEXELS
  VITE_PEXELS_API_KEY: "gpj1qjqnc3YK0Yfr6QEU45UEaiwzY0Ei8MabC0VltG5mSTF8cQiEGnjx"
  #Google
  VITE_GOOGLE_API_KEY: "AIzaSyDz_WmIAeG6BEgfqxtwIpbb27exbetxdyE"
  VITE_GOOGLE_SEARCH_ENGINE_ID: "565e00881ac074383"
  VITE_YOUTUBE_API_KEY: "AIzaSyDyQ9NXrZ1auVkKi6hSagjOQf8mAbKS8W0"
  YOUTUBE_API_KEY: "AIzaSyDyQ9NXrZ1auVkKi6hSagjOQf8mAbKS8W0"
  #Stripe
  VITE_STRIPE_PUBLISHABLE_KEY: "pk_test_51Qr2MLQ1fESgBlyzRl9JXXX27aJIdzM77o6ekHvpy9z6R7rVqCWSEnONJtulLwAAkaVVrhbl1ovqwePUICipc7OH00N5NbqRgK"
  STRIPE_SECRET_KEY: "sk_test_51Qr2MLQ1fESgBlyznIlqhrx6afNf2VChs8VFoYqoAaOPsBBmtGwhRhZGrA4S8UPBCxKcmCkTC5crELOzj0SDLab400cUQanL7T"
  VITE_APP_URL: "https://www.aigenthrive.com"
  STRIPE_WEBHOOK_SECRET: "whsec_lCbsCNbwHFsia1cCuAPgvfT0TfuwFFOE"

handlers:
  # API routes – send to server
  - url: /api/.*
    script: auto
    secure: always

  # Webhook route – handled by your server code
  - url: /webhook
    script: auto
    secure: always

  # Health check route
  - url: /_ah/health
    script: auto

  # Serve static assets (only if the file exists)
  - url: /(.*\.(css|js|png|jpg|svg|ico|mp4|html))$
    static_files: dist/\1
    upload: dist/.*\.(css|js|png|jpg|svg|ico|mp4|html)$
    secure: always
    http_headers:
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY
      X-XSS-Protection: '1; mode=block'

  # Catch-all handler for client-side routes
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
    secure: always
    http_headers:
      X-Content-Type-Options: nosniff
      X-Frame-Options: DENY
      X-XSS-Protection: '1; mode=block'

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

entrypoint: npm run start

service: default

instance_class: F2