runtime: nodejs22

env_variables:
  VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
  VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
  VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
  VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
  VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
  VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
  VITE_FIREBASE_MEASUREMENT_ID: ${VITE_FIREBASE_MEASUREMENT_ID}
  VITE_OPENAI_API_KEY: ${VITE_OPENAI_API_KEY}
  VITE_UNSPLASH_ACCESS_KEY: ${VITE_UNSPLASH_ACCESS_KEY}
  VITE_GOOGLE_API_KEY: ${VITE_GOOGLE_API_KEY}
  VITE_GOOGLE_SEARCH_ENGINE_ID: ${VITE_GOOGLE_SEARCH_ENGINE_ID}
  VITE_YOUTUBE_API_KEY: ${VITE_YOUTUBE_API_KEY}
  VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY}
  VITE_STRIPE_SECRET_KEY: ${VITE_STRIPE_SECRET_KEY}
  VITE_APP_URL: ${VITE_APP_URL}
  STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}

handlers:
  # Webhook route – handled by your server code
  - url: /webhook
    script: auto

  # Health check route
  - url: /_ah/health
    script: auto

  # Serve static assets (only if the file exists)
  - url: /(.*\.(css|js|png|jpg|svg|ico|mp4))$
    static_files: dist/\1
    upload: dist/.*\.(css|js|png|jpg|svg|ico|mp4)$

  # Catch-all handler for client-side routes
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

entrypoint: npm run start

service: default

instance_class: F2