runtime: nodejs22

env_variables:
  #Firebase
  VITE_FIREBASE_API_KEY: "AIzaSyAIwZAfPuPobcSEvh_JF4CamSfh13aODjI"
  VITE_FIREBASE_AUTH_DOMAIN: "aigen-app.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID: "aigen-app"
  VITE_FIREBASE_STORAGE_BUCKET: "aigen-app.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID: "73681948337"
  VITE_FIREBASE_APP_ID: "1:73681948337:web:bb7729568a7ec00c501c90"
  VITE_FIREBASE_MEASUREMENT_ID: "G-9PG3WXBSKF"
  #OpenAI
  VITE_OPENAI_API_KEY: "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"
  #PEXELS
  VITE_PEXELS_API_KEY: "gpj1qjqnc3YK0Yfr6QEU45UEaiwzY0Ei8MabC0VltG5mSTF8cQiEGnjx"
  #Google
  VITE_GOOGLE_API_KEY: "AIzaSyDCspyO9x2zLv7seleDISK60ikVBZJSt6c"
  VITE_GOOGLE_SEARCH_ENGINE_ID: "565e00881ac074383"
  YOUTUBE_API_KEY: "AIzaSyDyQ9NXrZ1auVkKi6hSagjOQf8mAbKS8W0"
  #Stripe
  VITE_STRIPE_PUBLISHABLE_KEY: "pk_test_51Qr2MLQ1fESgBlyzRl9JXXX27aJIdzM77o6ekHvpy9z6R7rVqCWSEnONJtulLwAAkaVVrhbl1ovqwePUICipc7OH00N5NbqRgK"
  STRIPE_SECRET_KEY: "sk_test_51Qr2MLQ1fESgBlyznIlqhrx6afNf2VChs8VFoYqoAaOPsBBmtGwhRhZGrA4S8UPBCxKcmCkTC5crELOzj0SDLab400cUQanL7T"
  VITE_APP_URL: "https://www.aigenthrive.com"
  STRIPE_WEBHOOK_SECRET: "whsec_lCbsCNbwHFsia1cCuAPgvfT0TfuwFFOE"

handlers:
  # Webhook route – handled by your server code
  - url: /webhook
    script: auto

  # Health check route
  - url: /_ah/health
    script: auto

  # Serve static assets (only if the file exists)
  - url: /(.*\.(css|js|png|jpg|svg|ico|mp4|html))$
    static_files: dist/\1
    upload: dist/.*\.(css|js|png|jpg|svg|ico|mp4|html)$

  # Catch-all handler for client-side routes
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

entrypoint: npm run start

service: default

instance_class: F2