runtime: nodejs18

env_variables:
  VITE_FIREBASE_API_KEY: ${VITE_FIREBASE_API_KEY}
  VITE_FIREBASE_AUTH_DOMAIN: ${VITE_FIREBASE_AUTH_DOMAIN}
  VITE_FIREBASE_PROJECT_ID: ${VITE_FIREBASE_PROJECT_ID}
  VITE_FIREBASE_STORAGE_BUCKET: ${VITE_FIREBASE_STORAGE_BUCKET}
  VITE_FIREBASE_MESSAGING_SENDER_ID: ${VITE_FIREBASE_MESSAGING_SENDER_ID}
  VITE_FIREBASE_APP_ID: ${VITE_FIREBASE_APP_ID}
  VITE_FIREBASE_MEASUREMENT_ID: ${VITE_FIREBASE_MEASUREMENT_ID}
  VITE_OPENAI_API_KEY: ${VITE_OPENAI_API_KEY}
  VITE_UNSPLASH_ACCESS_KEY: ${VITE_UNSPLASH_ACCESS_KEY}
  VITE_GOOGLE_API_KEY: ${VITE_GOOGLE_API_KEY}
  VITE_GOOGLE_SEARCH_ENGINE_ID: ${VITE_GOOGLE_SEARCH_ENGINE_ID}
  VITE_YOUTUBE_API_KEY: ${VITE_YOUTUBE_API_KEY}
  VITE_STRIPE_PUBLISHABLE_KEY: ${VITE_STRIPE_PUBLISHABLE_KEY}
  VITE_STRIPE_SECRET_KEY: ${VITE_STRIPE_SECRET_KEY}
  VITE_STRIPE_WEBHOOK_SECRET: ${VITE_STRIPE_WEBHOOK_SECRET}
  VITE_APP_URL: ${VITE_APP_URL}

handlers:
  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  - url: /(.*)
    static_files: dist/\1
    upload: dist/(.*)

  - url: /_ah/health
    script: auto

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5